apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: index.docker.io/jtrnc/petclinic:latest
        name: spring-petclinic
        ports:
        - containerPort: 8080
